// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijvvdcvzgjsjivustdgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqdnZkY3Z6Z2pzaml2dXN0ZGdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNzY3ODksImV4cCI6MjA1ODY1Mjc4OX0.8RiKCEiJMIarbpiw7gA8G9Gbal1MvShm1vqCshqx-zs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);